// frontend/src/components/layout/AppLayout.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { Menu, Moon, Sun } from "lucide-vue-next";
import Sidebar from "./Sidebar.vue";
import PageSkeleton from "./PageSkeleton.vue";
import ErrorBoundary from "./ErrorBoundary.vue";
import Toast from "@/components/ui/Toast.vue";
import { useRealtimeSocket } from "@/composables/useRealtimeSocket";

type Theme = "dark" | "light";
const collapsed = ref(false);
const mobileOpen = ref(false);
const theme = ref<Theme>(
  (localStorage.getItem("ackwrap.theme") as Theme) || "dark",
);
const reconcileError = ref("");
watch(
  theme,
  (value) => {
    document.documentElement.dataset.theme = value;
    localStorage.setItem("ackwrap.theme", value);
  },
  { immediate: true },
);
watch(reconcileError, (value) => {
  if (value)
    setTimeout(() => {
      reconcileError.value = "";
    }, 6000);
});
const { connected } = useRealtimeSocket((event) => {
  if (event.type !== "config.reconcile") return;
  const data = event.data as { status?: string; error?: string };
  if (data.status === "failed")
    reconcileError.value = data.error || "配置自动应用失败";
});
</script>
<template>
  <div class="flex h-screen bg-[var(--bg-base)] text-[var(--text-primary)]">
    <Toast :message="reconcileError" type="error" />
    <div
      v-if="mobileOpen"
      class="fixed inset-0 z-40 bg-black/50 backdrop-blur-sm lg:hidden"
      @click="mobileOpen = false"
    />
    <Sidebar
      :collapsed="collapsed"
      :mobile-open="mobileOpen"
      @toggle="collapsed = !collapsed"
      @close="mobileOpen = false"
    />
    <main
      id="main-content"
      class="flex min-w-0 flex-1 flex-col overflow-hidden"
    >
      <header
        class="flex h-[62px] shrink-0 items-center justify-between border-b border-[var(--border-light)] bg-[var(--header-bg)] px-5 backdrop-blur-xl"
      >
        <button
          class="flex h-9 w-9 items-center justify-center rounded-full border border-[var(--border-default)] bg-[var(--button-secondary-bg)] lg:hidden"
          title="打开导航"
          @click="mobileOpen = true"
        >
          <Menu :size="18" />
        </button>
        <div class="hidden w-5 lg:block" />
        <div class="ml-auto flex items-center gap-3 text-sm">
          <button
            class="inline-flex h-9 items-center gap-2 rounded-full border border-[var(--border-default)] bg-white/[0.08] px-3 text-xs"
            @click="theme = theme === 'dark' ? 'light' : 'dark'"
          >
            <Sun v-if="theme === 'dark'" :size="15" /><Moon
              v-else
              :size="15"
            />{{ theme === "dark" ? "白天" : "夜间" }}
          </button>
          <span class="inline-flex items-center gap-2"
            ><span
              class="h-2 w-2 rounded-full"
              :class="
                connected
                  ? 'bg-emerald-400 animate-status-pulse'
                  : 'bg-gray-500'
              "
            />{{ connected ? "已连接" : "连接中" }}</span
          >
        </div>
      </header>
      <div class="flex-1 overflow-auto">
        <div class="h-full px-4 py-5 sm:px-6 lg:px-7">
          <RouterView v-slot="{ Component }"
            ><ErrorBoundary
              ><Suspense
                ><component :is="Component" /><template #fallback
                  ><PageSkeleton /></template></Suspense></ErrorBoundary
          ></RouterView>
        </div>
      </div>
    </main>
  </div>
</template>

// frontend/src/components/layout/AppLayout.tsx
import { useEffect, useState } from 'react';
import { Moon, Sun } from 'lucide-react';
import { useRealtimeSocket } from '@/hooks/useRealtimeSocket';
import type { WSEvent } from '@/services/types';
import { Toast } from '@/components/ui/Toast';
import { Sidebar } from './Sidebar';

type ThemeMode = 'dark' | 'light';

export function AppLayout({ children }: { children: React.ReactNode }) {
  const [collapsed, setCollapsed] = useState(false);
  const [reconcileError, setReconcileError] = useState('');
  const [theme, setTheme] = useState<ThemeMode>(() => {
    if (typeof window === 'undefined') return 'dark';
    return (localStorage.getItem('ackwrap.theme') as ThemeMode) || 'dark';
  });

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    localStorage.setItem('ackwrap.theme', theme);
  }, [theme]);

  useRealtimeSocket((event: WSEvent) => {
    if (event.type !== 'config.reconcile') return;
    const data = event.data as { status?: string; error?: string };
    if (data.status === 'failed') {
      setReconcileError(data.error || '配置自动应用失败');
    }
  });

  useEffect(() => {
    if (!reconcileError) return;
    const timer = window.setTimeout(() => setReconcileError(''), 6000);
    return () => window.clearTimeout(timer);
  }, [reconcileError]);

  const toggleTheme = () => setTheme(value => value === 'dark' ? 'light' : 'dark');

  return (
    <div className="flex h-screen bg-[var(--bg-base)] text-[var(--text-primary)]">
      <Toast message={reconcileError} type="error" />
      <Sidebar collapsed={collapsed} onToggle={() => setCollapsed(v => !v)} />
      <main id="main-content" className="flex-1 flex flex-col min-w-0 overflow-hidden">
        <header className="flex items-center justify-between px-5 h-[62px] bg-[var(--header-bg)] border-b border-[var(--border-light)] backdrop-blur-xl shrink-0">
          <div className="hidden lg:block w-5" />
          <div className="ml-auto flex items-center gap-3 text-sm">
            <button onClick={toggleTheme} className="inline-flex h-9 items-center gap-2 rounded-full border border-[var(--border-default)] bg-white/[0.08] px-3 text-xs font-medium text-[var(--text-secondary)] transition hover:border-blue-400/30 hover:bg-blue-500/10 hover:text-[var(--text-primary)]" title={theme === 'dark' ? '切换到白天模式' : '切换到夜间模式'}>
              {theme === 'dark' ? <Sun size={15} /> : <Moon size={15} />}
              <span>{theme === 'dark' ? '白天' : '夜间'}</span>
            </button>
            <span id="ws-indicator" className="inline-flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-emerald-400 animate-status-pulse" id="ws-dot"></span>
              <span className="text-[var(--text-secondary)]" id="ws-text">已连接</span>
            </span>
          </div>
        </header>
        <div className="flex-1 overflow-auto">
          <div className="h-full px-4 py-5 sm:px-6 lg:px-7">
            {children}
          </div>
        </div>
      </main>
    </div>
  );
}
