// frontend/src/components/layout/Sidebar.tsx
import {
  LayoutDashboard,
  Settings,
  Activity,
  RadioTower,
  Network,
  Layers,
  ListChecks,
  ServerCog,
  FileCode,
  ChevronLeft,
  ChevronRight,
  Gauge,
} from 'lucide-react';
import { NavLink, useLocation } from 'react-router-dom';

const navItems = [
  { key: 'monitor', label: '仪表盘', icon: <Gauge size={18} />, path: '/' },
  { key: 'control', label: '控制面板', icon: <LayoutDashboard size={18} />, path: '/control' },
  { key: 'subscriptions', label: '订阅管理', icon: <RadioTower size={18} />, path: '/subscriptions' },
  { key: 'nodes', label: '节点管理', icon: <Network size={18} />, path: '/nodes' },
  { key: 'rules', label: '规则管理', icon: <ListChecks size={18} />, path: '/rules' },
  { key: 'collections', label: '策略组管理', icon: <Layers size={18} />, path: '/collections' },
  { key: 'dns', label: 'DNS 管理', icon: <ServerCog size={18} />, path: '/dns' },
  { key: 'config', label: '配置生成', icon: <FileCode size={18} />, path: '/config' },
  { key: 'logs', label: '日志', icon: <Activity size={18} />, path: '/logs' },
  { key: 'settings', label: '设置', icon: <Settings size={18} />, path: '/settings' },
];

export function Sidebar({ collapsed, onToggle }: { collapsed: boolean; onToggle: () => void }) {
  const location = useLocation();

  return (
    <aside className={`hidden lg:flex flex-col h-screen bg-[var(--bg-sidebar)] text-[var(--text-sidebar)] transition-[width] duration-300 shrink-0 ${collapsed ? 'w-16' : 'w-56'}`}>
      <div className="h-[62px] flex items-center justify-between px-5 border-b border-[var(--border-light)]">
        {!collapsed && (
          <div className="flex items-center gap-3">
            <img src="/favicon.png" alt="" className="h-9 w-9 shrink-0 drop-shadow-[0_0_16px_rgba(47,129,247,0.3)]" />
            <span className="text-[var(--text-primary)] font-bold text-lg tracking-wide">AckWrap</span>
          </div>
        )}
        {collapsed && <img src="/favicon.png" alt="Ackwrap" className="mx-auto h-9 w-9 drop-shadow-[0_0_14px_rgba(47,129,247,0.28)]" />}
      </div>
      <nav className="flex-1 px-4 py-5 overflow-y-auto space-y-2">
        {navItems.map(item => {
          const isActive = location.pathname === item.path;
          return (
            <NavLink
              key={item.key}
              to={item.path}
              className={`flex items-center gap-3 px-4 h-11 rounded-[var(--radius-lg)] border transition-colors duration-[var(--duration-fast)] ${collapsed ? 'justify-center px-0' : ''} ${isActive ? 'border-[var(--button-primary-border)] bg-[var(--button-primary-bg)] text-[var(--button-primary-text)] shadow-sm shadow-blue-500/10' : 'border-transparent text-[var(--text-sidebar)] hover:bg-[var(--bg-sidebar-hover)] hover:text-[var(--text-sidebar-active)]'}`}
            >
              <span className="shrink-0">{item.icon}</span>
              {!collapsed && <span className="text-sm truncate">{item.label}</span>}
            </NavLink>
          );
        })}
      </nav>
      <div className="border-t border-[var(--border-light)] p-3">
        <button onClick={onToggle} className="w-full h-8 flex items-center justify-center rounded hover:bg-[var(--bg-sidebar-hover)] text-[var(--text-sidebar)] hover:text-[var(--text-sidebar-active)] transition-colors cursor-pointer">
          {collapsed ? <ChevronRight size={16} /> : <ChevronLeft size={16} />}
        </button>
      </div>
    </aside>
  );
}

// frontend/src/components/layout/Sidebar.vue
<script setup lang="ts">
import {
  LayoutDashboard,
  Settings,
  Activity,
  RadioTower,
  Network,
  Layers,
  ListChecks,
  ServerCog,
  FileCode,
  ChevronLeft,
  ChevronRight,
  Gauge,
} from "lucide-vue-next";
withDefaults(defineProps<{ collapsed: boolean; mobileOpen?: boolean }>(), {
  mobileOpen: false,
});
defineEmits<{ toggle: []; close: [] }>();
const items = [
  ["控制面板", LayoutDashboard, "/"],
  ["仪表盘", Gauge, "/dashboard"],
  ["订阅管理", RadioTower, "/subscriptions"],
  ["节点管理", Network, "/nodes"],
  ["规则管理", ListChecks, "/rules"],
  ["策略组管理", Layers, "/collections"],
  ["DNS 管理", ServerCog, "/dns"],
  ["配置生成", FileCode, "/config"],
  ["日志", Activity, "/logs"],
  ["设置", Settings, "/settings"],
] as const;
</script>
<template>
  <aside
    class="h-screen shrink-0 flex-col bg-[var(--bg-sidebar)] text-[var(--text-sidebar)] transition-[width] duration-300"
    :class="[
      mobileOpen
        ? 'fixed inset-y-0 left-0 z-50 flex w-64 shadow-[var(--shadow-xl)]'
        : 'hidden lg:flex',
      collapsed ? 'lg:w-16' : 'lg:w-56',
    ]"
  >
    <div
      class="flex h-[62px] items-center justify-center border-b border-[var(--border-light)]"
    >
      <img src="/favicon.png" alt="AckWrap" class="h-9 w-9" /><b
        v-if="!collapsed"
        class="ml-3 text-lg text-[var(--text-primary)]"
        >AckWrap</b
      >
    </div>
    <nav class="flex-1 space-y-2 overflow-y-auto px-4 py-5">
      <RouterLink
        v-for="[label, icon, path] in items"
        :key="path"
        :to="path"
        class="flex h-11 items-center gap-3 rounded-[var(--radius-lg)] border border-transparent px-4"
        :class="[
          $route.path === path
            ? 'border-[var(--button-primary-border)] bg-[var(--button-primary-bg)] text-[var(--button-primary-text)]'
            : 'hover:bg-[var(--bg-sidebar-hover)]',
          collapsed && 'lg:justify-center lg:px-0',
        ]"
        @click="$emit('close')"
        ><component :is="icon" :size="18" /><span
          :class="collapsed ? 'lg:hidden' : ''"
          >{{ label }}</span
        ></RouterLink
      >
    </nav>
    <button
      class="m-3 hidden h-8 items-center justify-center lg:flex"
      @click="$emit('toggle')"
    >
      <ChevronRight v-if="collapsed" :size="16" /><ChevronLeft
        v-else
        :size="16"
      />
    </button>
  </aside>
</template>
