// frontend/src/pages/ControlPage.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import {
  Play,
  Square,
  RotateCcw,
  Download,
  AlertTriangle,
  Power,
  RefreshCw,
  FileCheck2,
  ShieldCheck,
  DatabaseZap,
  Activity,
  AlertCircle,
  CheckCircle2,
  Eraser,
  FileDown,
  ListX,
  XCircle,
} from "lucide-vue-next";
import { useRealtimeSocket } from "@/composables/useRealtimeSocket";
import { api } from "@/services/api";
import type {
  MaintenanceCheckResponse,
  RuntimeResponse,
  WSEvent,
} from "@/services/types";
import Button from "@/components/ui/Button.vue";
import PageHeader from "@/components/layout/PageHeader.vue";
import Toast from "@/components/ui/Toast.vue";
import ConfirmDialog from "@/components/ui/ConfirmDialog.vue";
import Modal from "@/components/ui/Modal.vue";
import ControlOverview from "./ControlOverview.vue";
import ControlNetworkOverview from "./ControlNetworkOverview.vue";
const runtime = ref<RuntimeResponse | null>(null),
  installStatus = ref<any>(null),
  configStatus = ref<any>(null),
  installProgress = ref<any>(null),
  guideDismissed = ref(false),
  inboundMode = ref("tun_mixed"),
  proxyMode = ref("rule"),
  modeChanging = ref(false),
  message = ref(""),
  messageType = ref<"success" | "error" | "info">("success"),
  refreshKey = ref(0),
  runtimeAction = ref(""),
  confirmFirewallReset = ref(false),
  confirmLogClear = ref(false),
  maintenanceReport = ref<MaintenanceCheckResponse | null>(null);
const labels: any = {
    running: "运行中",
    starting: "启动中",
    stopping: "停止中",
    stopped: "已停止",
    error: "异常",
    not_installed: "未安装",
    no_config: "无配置",
  },
  inboundLabels: any = {
    tun: "TUN 模式",
    mixed: "Mixed 模式",
    tun_mixed: "TUN + Mixed",
  },
  proxyLabels: any = {
    global: "全局模式",
    rule: "规则模式",
    direct: "直连模式",
  };
const rt = computed(() => runtime.value?.status || "not_installed"),
  isRunning = computed(() => rt.value === "running"),
  notInstalled = computed(
    () => runtime.value !== null && rt.value === "not_installed",
  ),
  noConfig = computed(() => rt.value === "no_config"),
  installing = computed(() =>
    ["downloading", "extracting"].includes(installStatus.value?.status),
  ),
  isWindows = computed(() => runtime.value?.platform === "windows"),
  unsupported = computed(() => !!runtime.value?.platform && !isWindows.value),
  currentVersion = computed(
    () => runtime.value?.version || installStatus.value?.version,
  ),
  latestVersion = computed(() => installStatus.value?.latest_version);
function newer(a?: string, b?: string) {
  if (!a || !b) return false;
  const p = (v: string) =>
    v.replace(/^v/, "").split(/[+-]/, 1)[0].split(".").map(Number);
  for (let i = 0; i < 3; i++)
    if ((p(a)[i] || 0) !== (p(b)[i] || 0))
      return (p(a)[i] || 0) > (p(b)[i] || 0);
  return false;
}
const updateAvailable = computed(() =>
    newer(latestVersion.value, currentVersion.value),
  ),
  showInstallGuide = computed(
    () =>
      !guideDismissed.value &&
      runtime.value !== null &&
      (notInstalled.value || installing.value),
  ),
  showConfigGuide = computed(
    () =>
      !guideDismissed.value &&
      !notInstalled.value &&
      !installing.value &&
      configStatus.value?.has_config === false,
  ),
  progress = computed(() => ({
    percent: Math.max(
      installProgress.value?.percent || 0,
      installStatus.value?.progress || 0,
    ),
    downloaded_bytes: installProgress.value?.downloaded_bytes || 0,
    total_bytes: installProgress.value?.total_bytes || 0,
  }));
let toastTimer: number,
  installTimer: number,
  cancelled = false;
function notify(v: string, t: "success" | "error" | "info" = "success") {
  message.value = v;
  messageType.value = t;
}
watch([message, messageType], () => {
  clearTimeout(toastTimer);
  if (message.value)
    toastTimer = window.setTimeout(
      () => (message.value = ""),
      messageType.value === "error" ? 5000 : 3000,
    );
});
async function initial() {
  try {
    runtime.value = await api.getRuntime();
    installStatus.value = await api.getInstallerStatus();
    if (runtime.value.status === "not_installed") return;
    configStatus.value = await api.getConfigStatus();
    inboundMode.value = (await api.getInboundMode()).mode;
    proxyMode.value = (await api.getProxyMode()).mode;
  } catch (e: any) {
    if (!cancelled)
      notify(`控制面板初始化失败: ${e?.message || "请求失败"}`, "error");
  }
}
async function action(fn: () => Promise<any>, label: string) {
  if (runtimeAction.value) return;
  runtimeAction.value = label;
  try {
    const r = await fn();
    notify(`${label} 成功${r?.message ? `: ${r.message}` : ""}`);
  } catch (e: any) {
    notify(`${label} 失败: ${e.message}`, "error");
  } finally {
    runtimeAction.value = "";
  }
  setTimeout(() => {
    api
      .getRuntime()
      .then((r) => (runtime.value = r))
      .catch(() => {});
    api
      .getConfigStatus()
      .then((r) => (configStatus.value = r))
      .catch(() => {});
    api
      .getInstallerStatus()
      .then((r) => (installStatus.value = r))
      .catch(() => {});
  }, 1000);
}

async function runNetworkCheck() {
  if (runtimeAction.value) return;
  runtimeAction.value = "网络自检";
  try {
    maintenanceReport.value = await api.networkCheck();
    notify(
      maintenanceReport.value.success
        ? "网络自检通过"
        : "网络自检发现需要处理的项目",
      maintenanceReport.value.success ? "success" : "info",
    );
  } catch (e: any) {
    notify(`网络自检失败: ${e.message}`, "error");
  } finally {
    runtimeAction.value = "";
  }
}

async function exportDiagnostics() {
  if (runtimeAction.value) return;
  runtimeAction.value = "导出诊断";
  try {
    const report = await api.getDiagnostics();
    const blob = new Blob([JSON.stringify(report, null, 2)], {
      type: "application/json;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `ackwrap-diagnostics-${new Date(report.generated_at)
      .toISOString()
      .replace(/[:.]/g, "-")}.json`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.setTimeout(() => URL.revokeObjectURL(url), 0);
    notify("脱敏诊断报告已导出");
  } catch (e: any) {
    notify(`导出诊断失败: ${e.message}`, "error");
  } finally {
    runtimeAction.value = "";
  }
}
async function install(label: string) {
  try {
    await api.install();
    installStatus.value = {
      ...installStatus.value,
      status: "downloading",
      progress: 0,
      message: "preparing download",
    };
    installProgress.value = null;
    notify(`${label}任务已启动`, "info");
  } catch (e: any) {
    notify(`${label}启动失败: ${e.message}`, "error");
  }
}
async function changeMode(kind: "inbound" | "proxy", mode: string) {
  if (isRunning.value || modeChanging.value) return;
  modeChanging.value = true;
  try {
    if (kind === "inbound") {
      await api.setInboundMode(mode);
      inboundMode.value = mode;
    } else {
      await api.setProxyMode(mode);
      proxyMode.value = mode;
    }
    notify(
      `${kind === "inbound" ? "运行" : "代理"}模式已切换为 ${(kind === "inbound" ? inboundLabels : proxyLabels)[mode]}`,
    );
  } catch (e: any) {
    notify(`切换模式失败: ${e.message}`, "error");
  } finally {
    modeChanging.value = false;
  }
}
useRealtimeSocket((e: WSEvent) => {
  const d: any = e.data;
  if (e.type === "runtime.status")
    runtime.value = { ...runtime.value, ...d } as RuntimeResponse;
  else if (e.type === "installer.progress") installProgress.value = d;
  else if (e.type === "installer.status") {
    installStatus.value = { ...installStatus.value, ...d };
    if (["done", "failed"].includes(d.status)) installProgress.value = null;
    if (d.status === "failed")
      notify(`安装失败: ${d.error || "请查看安装状态详情"}`, "error");
    if (d.status === "done") void initial();
  } else if (e.type === "core.status") {
    runtime.value = {
      ...runtime.value,
      status: d.status,
      pid: d.pid || 0,
    } as RuntimeResponse;
    if (d.status === "error" && d.error)
      notify(`核心异常: ${d.error}`, "error");
  } else if (e.type === "config.status") configStatus.value = d;
  else if (
    e.type === "subscription.sync" &&
    ["updated", "failed"].includes(d?.status)
  )
    refreshKey.value++;
  else if (
    [
      "subscription.sync_all",
      "route_rule_subscription.sync_all",
      "geo.sync_all",
    ].includes(e.type)
  ) {
    refreshKey.value++;
    notify(
      `${e.type}完成${d.failed ? `，${d.failed}/${d.total || 0} 项失败` : `，共 ${d.total || 0} 项`}`,
      d.failed ? "error" : "success",
    );
  }
});
watch(installing, (v) => {
  clearInterval(installTimer);
  if (v)
    installTimer = window.setInterval(async () => {
      try {
        const s = await api.getInstallerStatus();
        installStatus.value = s;
        if (["done", "failed"].includes(s.status)) installProgress.value = null;
        if (s.status === "done") void initial();
      } catch (e: any) {
        const m = `安装状态查询失败，后端连接已断开: ${e?.message || "连接被重置"}`;
        installStatus.value = {
          ...installStatus.value,
          status: "failed",
          error: m,
        };
        notify(m, "error");
      }
    }, 1000);
});
const modes = (kind: "proxy" | "inbound") =>
  kind === "proxy"
    ? [
        ["rule", "规则模式"],
        ["global", "全局模式"],
        ["direct", "直连模式"],
      ]
    : [
        ["tun_mixed", "TUN + Mixed"],
        ["tun", "TUN 模式"],
        ["mixed", "Mixed 模式"],
      ];
onMounted(initial);
onBeforeUnmount(() => {
  cancelled = true;
  clearInterval(installTimer);
});
</script>
<template>
  <div class="flex h-full flex-col">
    <Toast :message="message" :type="messageType" /><ConfirmDialog
      :open="confirmFirewallReset"
      title="重置 Windows 防火墙"
      message="此操作会清除并恢复系统防火墙规则，可能影响其他应用的网络访问。确认继续吗？"
      confirm-text="确认重置"
      danger
      @cancel="confirmFirewallReset = false"
      @confirm="
        confirmFirewallReset = false;
        action(api.resetFirewall, '重置防火墙');
      "
    /><ConfirmDialog
      :open="confirmLogClear"
      title="清理核心日志"
      message="此操作会清空当前内存中的核心日志，且无法恢复。确认继续吗？"
      confirm-text="确认清理"
      danger
      @cancel="confirmLogClear = false"
      @confirm="
        confirmLogClear = false;
        action(api.clearCoreLogs, '清理核心日志');
      "
    /><Modal
      :open="!!maintenanceReport"
      title="网络自检结果"
      size="md"
      @close="maintenanceReport = null"
    >
      <div class="space-y-2">
        <div
          v-for="check in maintenanceReport?.checks || []"
          :key="check.key"
          class="flex items-start gap-3 rounded-[var(--radius-lg)] border border-[var(--border-default)] bg-[var(--bg-base)] p-3"
        >
          <CheckCircle2
            v-if="check.status === 'pass'"
            :size="17"
            class="mt-0.5 shrink-0 text-[var(--color-success)]"
          />
          <AlertCircle
            v-else-if="check.status === 'warn'"
            :size="17"
            class="mt-0.5 shrink-0 text-[var(--color-warning)]"
          />
          <XCircle
            v-else
            :size="17"
            class="mt-0.5 shrink-0 text-[var(--color-error)]"
          />
          <div>
            <div class="font-medium text-[var(--text-primary)]">
              {{ check.label }}
            </div>
            <p class="mt-0.5 text-xs text-[var(--text-secondary)]">
              {{ check.message }}
            </p>
          </div>
        </div>
      </div> </Modal
    ><PageHeader title="控制面板" />
    <div
      v-if="showInstallGuide || showConfigGuide"
      class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4"
    >
      <div
        class="w-full max-w-md rounded-[var(--radius-xl)] border bg-[var(--bg-surface)] p-5"
      >
        <div class="flex gap-3">
          <AlertTriangle :size="20" />
          <div>
            <h3 class="font-semibold">
              {{ showInstallGuide ? "需要安装 sing-box" : "需要生成默认配置" }}
            </h3>
            <p class="text-sm">
              {{
                showInstallGuide
                  ? "控制面板检测到 sing-box 未安装，请先安装核心程序。"
                  : "已检测到 sing-box，但当前没有可用配置文件，是否生成默认配置？"
              }}
            </p>
          </div>
        </div>
        <div v-if="showInstallGuide && installing" class="mt-4">
          <div class="h-2 bg-white/10">
            <div
              class="h-full bg-blue-400"
              :style="{ width: `${Math.min(100, progress.percent)}%` }"
            />
          </div>
          <small>{{ progress.percent.toFixed(1) }}%</small>
        </div>
        <div v-if="installStatus?.error" class="mt-3 text-red-300">
          {{ installStatus.error }}
        </div>
        <div class="mt-5 flex justify-end gap-2">
          <Button variant="ghost" size="sm" @click="guideDismissed = true"
            >稍后处理</Button
          ><Button
            v-if="showInstallGuide"
            size="sm"
            :loading="installing"
            :disabled="installing"
            @click="install('安装')"
            >安装 sing-box</Button
          ><Button
            v-else
            size="sm"
            :disabled="isRunning || !!runtimeAction"
            @click="action(api.generateDefaultConfig, '生成默认配置')"
            >生成默认配置</Button
          >
        </div>
      </div>
    </div>
    <section
      v-if="notInstalled || noConfig"
      class="mt-4 rounded-[var(--radius-xl)] border border-orange-400/20 p-5"
    >
      <h3 class="font-semibold">
        {{ notInstalled ? "sing-box 未安装" : "配置文件不存在" }}
      </h3>
      <p class="text-sm">
        {{
          notInstalled
            ? "点击下方安装按钮下载并安装 sing-box。"
            : "sing-box 已安装但配置文件缺失，请生成默认配置。"
        }}
      </p>
    </section>
    <div
      class="mt-4 grid min-h-[720px] flex-1 items-stretch gap-4 lg:grid-cols-2 xl:grid-cols-12"
    >
      <section
        class="flex h-full flex-col rounded-[var(--radius-xl)] border bg-[var(--bg-surface)] p-5 xl:col-span-4"
      >
        <div class="flex gap-3">
          <Power :size="19" />
          <div>
            <h2 class="font-semibold">
              核心控制 <span class="text-xs">{{ labels[rt] }}</span>
            </h2>
            <small>sing-box 进程管理</small>
          </div>
        </div>
        <div class="mt-3 grid grid-cols-3 gap-2">
          <div
            v-for="x in [
              ['进程 ID', runtime?.pid || '-'],
              ['核心版本', currentVersion || '--'],
              [
                '配置状态',
                configStatus?.has_config && configStatus.valid
                  ? '校验通过'
                  : '需要处理',
              ],
            ]"
            :key="x[0]"
            class="bg-[var(--bg-base)] px-2 py-1.5"
          >
            <small>{{ x[0] }}</small
            ><b class="block truncate">{{ x[1] }}</b>
          </div>
        </div>
        <div class="mt-3 grid grid-cols-2 gap-2 px-1 sm:grid-cols-4">
          <button
            class="aw-control-action"
            :disabled="!!runtimeAction || isRunning || notInstalled || noConfig"
            @click="action(api.startCore, '启动')"
          >
            <Play :size="13" />启动核心</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction || !isRunning"
            @click="action(api.stopCore, '停止')"
          >
            <Square :size="13" />停止核心</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction || !isRunning"
            @click="action(api.restartCore, '重启')"
          >
            <RotateCcw :size="13" />重启核心</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction || notInstalled || noConfig"
            @click="action(api.reloadConfig, '重载配置')"
          >
            <RefreshCw :size="13" />重载配置
          </button>
        </div>
      </section>
      <section
        v-for="kind in ['proxy', 'inbound'] as const"
        :key="kind"
        class="flex h-full flex-col rounded-[var(--radius-xl)] border bg-[var(--bg-surface)] p-5 xl:col-span-4"
      >
        <h2>{{ kind === "proxy" ? "代理模式" : "运行模式" }}</h2>
        <p class="text-xs">
          {{
            kind === "proxy"
              ? "决定流量使用规则、代理或直连"
              : "选择流量进入 sing-box 的方式"
          }}
        </p>
        <div
          class="my-auto grid grid-cols-3 gap-1 rounded-[var(--radius-lg)] bg-[var(--bg-base)] p-1"
        >
          <label
            v-for="m in modes(kind)"
            :key="m[0]"
            class="flex h-8 min-w-0 items-center justify-center truncate rounded-[var(--radius-md)] px-2 text-center text-xs transition-colors"
            :class="[
              (kind === 'proxy' ? proxyMode : inboundMode) === m[0]
                ? 'bg-[var(--button-primary-bg)] text-[var(--button-primary-text)] shadow-sm'
                : 'text-[var(--text-secondary)] hover:bg-[var(--button-secondary-hover)]',
              isRunning || modeChanging || !!runtimeAction
                ? 'cursor-not-allowed opacity-50'
                : 'cursor-pointer',
            ]"
            ><input
              type="radio"
              class="sr-only"
              :checked="(kind === 'proxy' ? proxyMode : inboundMode) === m[0]"
              :disabled="isRunning || modeChanging || !!runtimeAction"
              @change="changeMode(kind, m[0])"
            />{{ m[1] }}</label
          >
        </div>
        <small>{{
          isRunning
            ? "停止核心后可修改"
            : `当前模式：${kind === "proxy" ? proxyLabels[proxyMode] : inboundLabels[inboundMode]}`
        }}</small>
      </section>
      <section
        class="flex h-full flex-col rounded-[var(--radius-xl)] border bg-[var(--bg-surface)] p-5 xl:col-span-4"
      >
        <h2>高级维护</h2>
        <p class="text-xs">连接与系统网络维护操作</p>
        <div class="my-auto grid grid-cols-2 gap-2 px-1 sm:grid-cols-3">
          <button
            class="aw-control-action"
            :disabled="!!runtimeAction || !isRunning"
            @click="action(api.closeConnections, '关闭连接')"
          >
            <ShieldCheck :size="13" />关闭连接</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction || !isRunning"
            @click="action(api.flushCoreDNS, '清理核心 DNS')"
          >
            <DatabaseZap :size="13" />清理核心 DNS</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction || !isRunning"
            @click="action(api.flushFakeIP, '清理 FakeIP')"
          >
            <Eraser :size="13" />清理 FakeIP</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction"
            @click="runNetworkCheck"
          >
            <Activity :size="13" />网络自检</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction || unsupported"
            @click="action(api.flushDNS, '清理系统 DNS')"
          >
            <RefreshCw :size="13" />清理系统 DNS</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction"
            @click="confirmLogClear = true"
          >
            <ListX :size="13" />清理核心日志</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction"
            @click="exportDiagnostics"
          >
            <FileDown :size="13" />导出诊断</button
          ><button
            class="aw-control-action"
            :disabled="!!runtimeAction || notInstalled"
            @click="action(api.checkUpdate, '检查更新')"
          >
            <FileCheck2 :size="13" />检查更新</button
          ><button
            class="aw-control-action aw-action-danger"
            :disabled="!!runtimeAction || unsupported"
            @click="confirmFirewallReset = true"
          >
            <AlertTriangle :size="13" />重置防火墙
          </button>
        </div>
      </section>
      <ControlOverview
        :refresh-key="refreshKey"
        :config-status="configStatus"
        :proxy-mode="proxyMode"
        @message="notify"
        @resources-changed="
          refreshKey++;
          api.getConfigStatus().then((r) => (configStatus = r));
        "
        ><template #installation
          ><h3>安装信息</h3>
          <div class="grid grid-cols-3 gap-2">
            <div>
              状态<br /><b>{{ installStatus?.status || "未安装" }}</b>
            </div>
            <div>
              当前<br /><b>{{ currentVersion || "--" }}</b>
            </div>
            <div>
              最新<br /><b>{{ latestVersion || "--" }}</b>
            </div>
          </div>
          <div v-if="installing" class="mt-3">
            {{ progress.percent.toFixed(1) }}%
          </div>
          <Button
            class="mt-3"
            full-width
            size="sm"
            :disabled="installing || isRunning"
            :loading="installing"
            @click="install(updateAvailable ? '更新' : '安装')"
            ><Download :size="14" />{{
              updateAvailable
                ? `更新至 ${latestVersion}`
                : installStatus?.status === "done"
                  ? "重新安装"
                  : "安装"
            }}</Button
          ></template
        ></ControlOverview
      ><ControlNetworkOverview
        :is-running="isRunning"
        :proxy-port="runtime?.proxy_port || 0"
        @message="notify"
      />
    </div>
  </div>
</template>

// frontend/src/pages/ControlPage.tsx
import React from 'react';
import { Play, Square, RotateCcw, Download, AlertTriangle, Power, RefreshCw, FileCheck2, ShieldCheck, DatabaseZap } from 'lucide-react';
import { useRealtimeSocket } from '@/hooks/useRealtimeSocket';
import { api } from '@/services/api';
import type { WSEvent } from '@/services/types';
import { Button } from '@/components/ui/Button';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { PageHeader } from '@/components/layout/PageHeader';
import { Toast } from '@/components/ui/Toast';

function Panel({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return (
    <section className={`rounded-[var(--radius-xl)] border border-[var(--border-default)] bg-[linear-gradient(180deg,rgba(20,33,52,0.92),rgba(16,27,43,0.74))] p-5 shadow-[var(--shadow-card)] ${className}`}>
      {children}
    </section>
  );
}

function PanelTitle({ title, extra }: { title: string; extra?: React.ReactNode }) {
  return (
    <div className="mb-4 flex items-center justify-between">
      <h2 className="text-base font-semibold text-white">{title}</h2>
      {extra}
    </div>
  );
}

const runtimeStatusMap: Record<string, { label: string; badge: string; dot: string }> = {
  running: { label: '运行中', badge: 'bg-emerald-500/15 text-emerald-300 border-emerald-400/20', dot: 'bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.6)]' },
  starting: { label: '启动中', badge: 'bg-blue-500/15 text-blue-300 border-blue-400/20', dot: 'bg-blue-400 animate-status-pulse' },
  stopping: { label: '停止中', badge: 'bg-yellow-500/15 text-yellow-300 border-yellow-400/20', dot: 'bg-yellow-400 animate-status-pulse' },
  stopped: { label: '已停止', badge: 'bg-slate-500/15 text-slate-300 border-slate-400/20', dot: 'bg-slate-400' },
  error: { label: '异常', badge: 'bg-red-500/15 text-red-300 border-red-400/20', dot: 'bg-red-400' },
  not_installed: { label: '未安装', badge: 'bg-red-500/15 text-red-300 border-red-400/20', dot: 'bg-red-400' },
  no_config: { label: '无配置', badge: 'bg-orange-500/15 text-orange-300 border-orange-400/20', dot: 'bg-orange-400' },
};

const installLabel: Record<string, string> = {
  idle: '未安装', downloading: '下载中', extracting: '解压中', done: '已安装', failed: '失败',
};

function isVersionNewer(candidate?: string, current?: string) {
  if (!candidate || !current) return false;
  const parse = (value: string) => value.replace(/^v/, '').split(/[+-]/, 1)[0].split('.').map(part => Number(part) || 0);
  const left = parse(candidate);
  const right = parse(current);
  for (let index = 0; index < 3; index += 1) {
    if ((left[index] || 0) !== (right[index] || 0)) return (left[index] || 0) > (right[index] || 0);
  }
  return false;
}

function RuntimeAction({ icon, label, tone = 'default', disabled = false, onClick }: { icon: React.ReactNode; label: string; tone?: 'default' | 'danger'; disabled?: boolean; onClick?: () => void }) {
  return (
    <button
      disabled={disabled}
      onClick={onClick}
      className={`inline-flex h-8 items-center justify-center gap-1.5 rounded-[6px] border px-2.5 text-xs font-medium transition ${
        tone === 'danger'
          ? 'border-red-400/25 bg-red-500/10 text-red-200 hover:border-red-300/40 hover:bg-red-500/15'
          : 'border-[var(--border-default)] bg-white/[0.04] text-[var(--text-secondary)] hover:border-blue-400/30 hover:bg-blue-500/10 hover:text-white'
      }`}
    >
      {icon}{label}
    </button>
  );
}

function ModeOption({ name, value, checked, title, description, recommended = false, disabled = false, onChange }: { name: string; value: string; checked: boolean; title: string; description: string; recommended?: boolean; disabled?: boolean; onChange: (value: string) => void }) {
  return (
    <label
      className={`flex items-center justify-between gap-3 rounded-lg border px-3 py-2.5 transition ${disabled ? 'cursor-not-allowed opacity-55' : 'cursor-pointer'} ${
        checked
          ? 'border-blue-400/45 bg-blue-500/10 text-[var(--text-primary)]'
          : `border-transparent bg-[var(--bg-base)] text-[var(--text-secondary)] ${disabled ? '' : 'hover:border-[var(--border-default)] hover:bg-[var(--bg-sidebar-hover)]'}`
      }`}
    >
      <input
        type="radio"
        name={name}
        value={value}
        checked={checked}
        disabled={disabled}
        onChange={(event) => onChange(event.target.value)}
        className="sr-only"
      />
      <span className="min-w-0">
        <span className="flex items-center gap-1.5">
          <span className="text-sm font-semibold">{title}</span>
          {recommended && <span className="rounded bg-blue-500/15 px-1.5 py-0.5 text-[10px] text-blue-200">推荐</span>}
        </span>
        <span className="mt-0.5 block text-xs text-[var(--text-tertiary)]">{description}</span>
      </span>
      <span className={`h-2.5 w-2.5 shrink-0 rounded-full ${checked ? 'bg-blue-300 shadow-[0_0_8px_rgba(96,165,250,0.7)]' : 'bg-[var(--border-default)]'}`} />
    </label>
  );
}

export function ControlPage() {
  const [runtime, setRuntime] = React.useState<{ status: string; pid?: number; version?: string } | null>(null);
  const [installStatus, setInstallStatus] = React.useState<{ status: string; version?: string; latest_version?: string; progress?: number; message?: string; error?: string } | null>(null);
  const [configStatus, setConfigStatus] = React.useState<{ has_config: boolean; valid: boolean; file_name?: string; updated_at?: number; error?: string } | null>(null);
  const [installProgress, setInstallProgress] = React.useState<{ percent: number; downloaded_bytes: number; total_bytes: number } | null>(null);
  const [guideDismissed, setGuideDismissed] = React.useState(false);
  const [inboundMode, setInboundMode] = React.useState<string>('tun_mixed');
  const [proxyMode, setProxyMode] = React.useState<string>('rule');
  const [modeChanging, setModeChanging] = React.useState(false);
  const [message, setMessage] = React.useState('');
  const [messageType, setMessageType] = React.useState<'success' | 'error' | 'info'>('success');

  useRealtimeSocket((event: WSEvent) => {
    console.log('[WS]', event.type, event.data);
    switch (event.type) {
      case 'runtime.status': setRuntime(event.data as any); break;
      case 'installer.status': {
        const status = event.data as any;
        setInstallStatus(previous => ({ ...previous, ...status }));
        if (status.status === 'done' || status.status === 'failed') {
          setInstallProgress(null);
        }
        if (status.status === 'done') {
          api.getRuntime().then(setRuntime).catch(() => {});
        }
        break;
      }
      case 'installer.progress': setInstallProgress(event.data as any); break;
      case 'core.status': {
        const d = event.data as any;
        console.log('[WS] core.status -> mapping to runtime', d.status, d.pid);
        setRuntime(prev => ({ ...prev, status: d.status, pid: d.pid || 0 }));
        break;
      }
      case 'config.status': setConfigStatus(event.data as any); break;
    }
  });

  const showMessage = (msg: string, type: 'success' | 'error' | 'info' = 'success') => {
    setMessage(msg);
    setMessageType(type);
  };

  React.useEffect(() => {
    if (!message) return;
    const timer = window.setTimeout(() => setMessage(''), messageType === 'error' ? 5000 : 3000);
    return () => window.clearTimeout(timer);
  }, [message, messageType]);

  React.useEffect(() => {
    let cancelled = false;

    async function checkInitialState() {
      try {
        const runtimeStatus = await api.getRuntime();
        if (cancelled) return;
        setRuntime(runtimeStatus);

        const installerStatus = await api.getInstallerStatus();
        if (cancelled) return;
        setInstallStatus(installerStatus);

        if (runtimeStatus.status === 'not_installed') {
          return;
        }

        const config = await api.getConfigStatus();
        if (cancelled) return;
        setConfigStatus(config);

        // 加载运行模式
        const modeResp = await api.getInboundMode();
        if (cancelled) return;
        setInboundMode(modeResp.mode);

        // 加载代理模式
        const proxyModeResp = await api.getProxyMode();
        if (cancelled) return;
        setProxyMode(proxyModeResp.mode);
      } catch {
        // API errors are surfaced by action feedback and websocket updates.
      }
    }

    checkInitialState();
    return () => { cancelled = true; };
  }, []);

  const rt = runtime?.status || 'not_installed';
  const isRunning = rt === 'running';
  const isRuntimeChecked = runtime !== null;
  const isNotInstalled = isRuntimeChecked && rt === 'not_installed';
  const isNoConfig = rt === 'no_config';
  const isInstalling = installStatus?.status === 'downloading' || installStatus?.status === 'extracting';
  const currentVersion = runtime?.version || installStatus?.version;
  const latestVersion = installStatus?.latest_version;
  const updateAvailable = isVersionNewer(latestVersion, currentVersion);
  const view = runtimeStatusMap[rt] || runtimeStatusMap.not_installed;
  const showInstallGuide = !guideDismissed && isRuntimeChecked && (isNotInstalled || isInstalling);
  const showConfigGuide = !guideDismissed && !isNotInstalled && !isInstalling && configStatus?.has_config === false;
  const displayedInstallProgress = {
    percent: Math.max(installProgress?.percent ?? 0, installStatus?.progress ?? 0),
    downloaded_bytes: installProgress?.downloaded_bytes ?? 0,
    total_bytes: installProgress?.total_bytes ?? 0,
  };

  const doAction = async (fn: () => Promise<any>, label: string) => {
    try {
      const res = await fn();
      showMessage(`${label} 成功${res?.message ? `: ${res.message}` : ''}`);
    } catch (e: any) {
      showMessage(`${label} 失败: ${e.message}`, 'error');
    }
    setTimeout(() => {
      console.log('[REST] re-fetching runtime status after action:', label);
      api.getRuntime().then(r => { console.log('[REST] runtime:', r); setRuntime(r); }).catch(() => {});
      api.getConfigStatus().then(c => setConfigStatus(c)).catch(() => {});
      api.getInstallerStatus().then(i => setInstallStatus(i)).catch(() => {});
    }, 1000);
  };

  const installCore = async (label: string) => {
    try {
      await api.install();
      setInstallStatus(previous => ({ ...previous, status: 'downloading', progress: 0, message: 'preparing download', error: undefined }));
      setInstallProgress(null);
      showMessage(`${label}任务已启动`, 'info');
    } catch (e: any) {
      showMessage(`${label}启动失败: ${e.message}`, 'error');
    }
  };

  React.useEffect(() => {
    if (!isInstalling) return;

    let cancelled = false;
    let refreshing = false;
    const refresh = async () => {
      if (refreshing) return;
      refreshing = true;
      try {
        const status = await api.getInstallerStatus();
        if (cancelled) return;
        setInstallStatus(status);
        if (status.status === 'done' || status.status === 'failed') setInstallProgress(null);
        if (status.status === 'done') api.getRuntime().then(setRuntime).catch(() => {});
      } catch (error: any) {
        if (cancelled) return;
        const detail = error?.message || '连接被重置';
        const errorMessage = `安装状态查询失败，后端连接已断开: ${detail}`;
        setInstallStatus(previous => ({ ...previous, status: 'failed', error: errorMessage }));
        setInstallProgress(null);
        showMessage(errorMessage, 'error');
      } finally {
        refreshing = false;
      }
    };

    const timer = window.setInterval(refresh, 1000);
    return () => {
      cancelled = true;
      window.clearInterval(timer);
    };
  }, [isInstalling]);

  const changeInboundMode = async (mode: string) => {
    if (isRunning || modeChanging) return;
    setModeChanging(true);
    try {
      await api.setInboundMode(mode);
      setInboundMode(mode);
      showMessage(`运行模式已切换为 ${inboundModeLabels[mode]}`);
    } catch (e: any) {
      showMessage(`切换运行模式失败: ${e.message}`, 'error');
    } finally {
      setModeChanging(false);
    }
  };

  const changeProxyMode = async (mode: string) => {
    if (isRunning || modeChanging) return;
    setModeChanging(true);
    try {
      await api.setProxyMode(mode);
      setProxyMode(mode);
      showMessage(`代理模式已切换为 ${proxyModeLabels[mode]}`);
    } catch (e: any) {
      showMessage(`切换代理模式失败: ${e.message}`, 'error');
    } finally {
      setModeChanging(false);
    }
  };

  const inboundModeLabels: Record<string, string> = {
    'tun': 'TUN 模式',
    'mixed': 'Mixed 模式',
    'tun_mixed': 'TUN + Mixed',
  };

  const proxyModeLabels: Record<string, string> = {
    'global': '全局模式',
    'rule': '规则模式',
    'direct': '直连模式',
  };

  return (
    <div className="flex flex-col h-full">
      <Toast message={message} type={messageType} />
      <PageHeader title="控制面板" />

      {(showInstallGuide || showConfigGuide) && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4 backdrop-blur-sm">
          <div className="w-full max-w-md rounded-[var(--radius-xl)] border border-[var(--border-default)] bg-[linear-gradient(180deg,rgba(20,33,52,0.98),rgba(16,27,43,0.96))] p-5 shadow-[var(--shadow-card)]">
            <div className="flex items-start gap-3">
              <div className={`mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${showInstallGuide ? 'bg-red-500/15 text-red-300' : 'bg-orange-500/15 text-orange-300'}`}>
                <AlertTriangle size={20} />
              </div>
              <div className="min-w-0 flex-1">
                <h3 className="text-base font-semibold text-white">{showInstallGuide ? '需要安装 sing-box' : '需要生成默认配置'}</h3>
                <p className="mt-1 text-sm text-[var(--text-secondary)]">
                  {showInstallGuide ? '控制面板检测到 sing-box 未安装，请先安装核心程序。' : '已检测到 sing-box，但当前没有可用配置文件，是否生成默认配置？'}
                </p>
              </div>
            </div>

            {showInstallGuide && isInstalling && (
              <div className="mt-4">
                <div className="h-2 overflow-hidden rounded-full bg-white/[0.08]">
                  <div className="h-full rounded-full bg-blue-400 transition-all" style={{ width: `${Math.min(100, displayedInstallProgress.percent)}%` }} />
                </div>
                <div className="mt-1 text-xs text-[var(--text-tertiary)]">
                  {displayedInstallProgress.percent.toFixed(1)}%
                  {displayedInstallProgress.total_bytes > 0 && ` · ${(displayedInstallProgress.downloaded_bytes / 1024 / 1024).toFixed(1)} MB / ${(displayedInstallProgress.total_bytes / 1024 / 1024).toFixed(1)} MB`}
                </div>
              </div>
            )}

            <div className="mt-5 flex items-center justify-end gap-2">
              <Button size="sm" variant="ghost" onClick={() => setGuideDismissed(true)}>稍后处理</Button>
              {showInstallGuide ? (
                <Button size="sm" variant="primary" icon={<Download size={14} />} loading={isInstalling} disabled={isInstalling} onClick={() => installCore('安装')}>{isInstalling ? '安装中...' : '安装 sing-box'}</Button>
              ) : (
                <Button size="sm" variant="primary" disabled={isRunning} onClick={() => doAction(api.generateDefaultConfig, '生成默认配置')}>生成默认配置</Button>
              )}
            </div>
          </div>
        </div>
      )}

      {isNotInstalled && (
        <section className="shrink-0 rounded-[var(--radius-xl)] border border-red-400/20 bg-[linear-gradient(135deg,rgba(248,81,73,0.08),rgba(47,129,247,0.04))] p-5">
          <div className="flex items-start gap-3">
            <div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-red-500/15 text-red-300"><AlertTriangle size={18} /></div>
            <div className="min-w-0 flex-1">
              <h3 className="text-base font-semibold text-white">sing-box 未安装</h3>
              <p className="mt-1 text-sm text-[var(--text-secondary)]">点击下方"安装"按钮下载并安装 sing-box。</p>
            </div>
          </div>
        </section>
      )}

      {isNoConfig && (
        <section className="shrink-0 rounded-[var(--radius-xl)] border border-orange-400/20 bg-[linear-gradient(135deg,rgba(251,146,60,0.08),rgba(47,129,247,0.04))] p-5 mt-4">
          <div className="flex items-start gap-3">
            <div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-orange-500/15 text-orange-300"><AlertTriangle size={18} /></div>
            <div className="min-w-0 flex-1">
              <h3 className="text-base font-semibold text-white">配置文件不存在</h3>
              <p className="mt-1 text-sm text-[var(--text-secondary)]">sing-box 已安装但配置文件缺失，请在下方生成默认配置。</p>
            </div>
          </div>
        </section>
      )}

      <div className="shrink-0 grid grid-cols-1 gap-4 mt-4 lg:grid-cols-3">
        {/* Status Panel */}
        <Panel className="h-full">
          <div className="mb-2 text-sm font-semibold text-white">服务状态</div>
          <div className="flex flex-1 flex-col justify-between gap-2">
            <div className="flex items-center gap-3">
              <div className={`relative flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${isRunning ? 'bg-emerald-500/15 text-emerald-300' : 'bg-slate-500/15 text-slate-300'}`}>
                <Power size={18} />
                <span className={`absolute -right-0.5 -top-0.5 h-2.5 w-2.5 rounded-full ${view.dot} ${isRunning ? 'animate-status-pulse' : ''}`} />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-base font-semibold text-white">sing-box</span>
                  <span className={`rounded-md border px-2 py-0.5 text-xs font-medium ${view.badge}`}>{view.label}</span>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-2">
              <div className="rounded-lg bg-white/[0.04] px-3 py-1">
                <div className="text-[10px] uppercase tracking-[0.12em] text-[var(--text-tertiary)]">进程ID</div>
                <div className="mt-0.5 text-sm font-semibold text-white">{runtime?.pid || '-'}</div>
              </div>
              <div className="rounded-lg bg-white/[0.04] px-3 py-1">
                <div className="text-[10px] uppercase tracking-[0.12em] text-[var(--text-tertiary)]">状态</div>
                <div className="mt-0.5 text-sm font-semibold text-white">{view.label}</div>
              </div>
              <div className="rounded-lg bg-white/[0.04] px-3 py-1">
                <div className="text-[10px] uppercase tracking-[0.12em] text-[var(--text-tertiary)]">版本</div>
                <div className="mt-0.5 text-sm font-semibold text-white">{runtime?.version || installStatus?.version || '--'}</div>
              </div>
            </div>
          </div>
        </Panel>

        {/* Actions Panel */}
        <Panel className="h-full">
          <div className="mb-2">
            <div className="text-sm font-semibold text-white">服务操作</div>
            <div className="mt-0.5 text-xs text-[var(--text-tertiary)]">控制 sing-box 核心运行状态</div>
          </div>
          <div className="grid grid-cols-2 gap-x-2 gap-y-3">
            <RuntimeAction icon={<Play size={14} />} label="启动核心" disabled={isRunning || isNotInstalled || isNoConfig} onClick={() => doAction(api.startCore, '启动')} />
            <RuntimeAction icon={<Square size={14} />} label="停止核心" tone="danger" disabled={!isRunning} onClick={() => doAction(api.stopCore, '停止')} />
            <RuntimeAction icon={<RotateCcw size={14} />} label="重启核心" disabled={!isRunning} onClick={() => doAction(api.restartCore, '重启')} />
            <RuntimeAction icon={<RefreshCw size={14} />} label="重载配置" disabled={isNotInstalled || isNoConfig} onClick={() => doAction(api.reloadConfig, '重载配置')} />
          </div>
        </Panel>

        {/* 高级维护 */}
        <Panel className="h-full">
          <div className="mb-2">
            <div className="text-sm font-semibold text-white">高级维护</div>
            <div className="mt-0.5 text-xs text-[var(--text-tertiary)]">低频维护动作，按需使用</div>
          </div>
          <div className="grid grid-cols-2 gap-x-2 gap-y-3">
            <RuntimeAction icon={<ShieldCheck size={14} />} label="关闭连接" disabled={!isRunning} onClick={() => doAction(api.closeConnections, '关闭连接')} />
            <RuntimeAction icon={<RefreshCw size={14} />} label="重置防火墙" onClick={() => doAction(api.resetFirewall, '重置防火墙')} />
            <RuntimeAction icon={<DatabaseZap size={14} />} label="清理DNS缓存" onClick={() => doAction(api.flushDNS, '清理 DNS 缓存')} />
            <RuntimeAction icon={<FileCheck2 size={14} />} label="检查更新" onClick={() => doAction(api.checkUpdate, '检查更新')} />
          </div>
        </Panel>
      </div>

      {/* 模式配置 */}
      <div className="shrink-0 grid grid-cols-1 gap-4 mt-4 md:grid-cols-2">
        <Panel className="h-full">
          <PanelTitle title="运行模式" extra={<span className="text-xs text-[var(--text-tertiary)]">{isRunning ? '停止核心后可修改' : 'Inbound'}</span>} />
          <div className="space-y-1.5">
            <ModeOption
              name="inbound-mode"
              value="tun_mixed"
              checked={inboundMode === 'tun_mixed'}
              title="TUN + Mixed"
              description="透明代理 + 端口"
              recommended
              disabled={isRunning || modeChanging}
              onChange={changeInboundMode}
            />
            <ModeOption
              name="inbound-mode"
              value="tun"
              checked={inboundMode === 'tun'}
              title="TUN 模式"
              description="纯透明代理"
              disabled={isRunning || modeChanging}
              onChange={changeInboundMode}
            />
            <ModeOption
              name="inbound-mode"
              value="mixed"
              checked={inboundMode === 'mixed'}
              title="Mixed 模式"
              description="SOCKS5 + HTTP 混合端口"
              disabled={isRunning || modeChanging}
              onChange={changeInboundMode}
            />
          </div>
        </Panel>

        <Panel className="h-full">
          <PanelTitle title="代理模式" extra={<span className="text-xs text-[var(--text-tertiary)]">{isRunning ? '停止核心后可修改' : 'Route'}</span>} />
          <div className="space-y-1.5">
            <ModeOption
              name="proxy-mode"
              value="rule"
              checked={proxyMode === 'rule'}
              title="规则模式"
              description="根据规则自动分流"
              recommended
              disabled={isRunning || modeChanging}
              onChange={changeProxyMode}
            />
            <ModeOption
              name="proxy-mode"
              value="global"
              checked={proxyMode === 'global'}
              title="全局模式"
              description="所有流量走代理"
              disabled={isRunning || modeChanging}
              onChange={changeProxyMode}
            />
            <ModeOption
              name="proxy-mode"
              value="direct"
              checked={proxyMode === 'direct'}
              title="直连模式"
              description="所有流量直连"
              disabled={isRunning || modeChanging}
              onChange={changeProxyMode}
            />
          </div>
        </Panel>
      </div>

      {/* 安装维护 */}
      <div className="shrink-0 mt-4">
        <Panel>
          <PanelTitle title="安装维护" extra={<span className="text-xs text-[var(--text-tertiary)]">GitHub Release</span>} />
          <div className="grid grid-cols-3 gap-2">
            <div className="rounded-lg bg-white/[0.04] px-3 py-2">
              <div className="text-[10px] uppercase tracking-[0.12em] text-[var(--text-tertiary)]">安装状态</div>
              <div className="mt-1 flex items-center gap-2 text-sm font-semibold text-white">
                <StatusBadge status={installStatus?.status === 'done' ? 'online' : installStatus?.status === 'failed' ? 'error' : isInstalling ? 'pending' : 'offline'} />
                <span className={installStatus?.status === 'failed' ? 'text-red-300' : ''}>{installLabel[installStatus?.status || 'idle'] || installStatus?.status || '未安装'}</span>
              </div>
            </div>
            <div className="rounded-lg bg-white/[0.04] px-3 py-2">
              <div className="text-[10px] uppercase tracking-[0.12em] text-[var(--text-tertiary)]">当前版本</div>
              <div className="mt-1 text-sm font-semibold text-white">{currentVersion || '--'}</div>
            </div>
            <div className="rounded-lg bg-white/[0.04] px-3 py-2">
              <div className="text-[10px] uppercase tracking-[0.12em] text-[var(--text-tertiary)]">最新版本</div>
              <div className={`mt-1 text-sm font-semibold ${updateAvailable ? 'text-amber-300' : 'text-white'}`}>{latestVersion || '--'}</div>
            </div>
          </div>

          {installStatus?.error && <div className="mt-2 text-xs text-red-300">{installStatus.error}</div>}
          {isInstalling && (
            <div className="mt-3">
              <div className="h-2 overflow-hidden rounded-full bg-white/[0.08]">
                <div className="h-full rounded-full bg-blue-400 transition-all" style={{ width: `${Math.min(100, displayedInstallProgress.percent)}%` }} />
              </div>
              <div className="mt-1 text-xs text-[var(--text-tertiary)]">
                {displayedInstallProgress.percent.toFixed(1)}%
                {displayedInstallProgress.total_bytes > 0 && ` · ${(displayedInstallProgress.downloaded_bytes / 1024 / 1024).toFixed(1)} MB / ${(displayedInstallProgress.total_bytes / 1024 / 1024).toFixed(1)} MB`}
              </div>
            </div>
          )}

          <div className="mt-3 flex justify-end">
            <Button variant="primary" size="sm" icon={<Download size={14} />} disabled={isInstalling || isRunning} onClick={() => installCore(updateAvailable ? '更新' : '安装')} loading={isInstalling}>
              {isInstalling ? (updateAvailable ? '更新中...' : '安装中...') : updateAvailable ? `更新至 ${latestVersion}` : installStatus?.status === 'done' ? '重新安装' : '安装'}
            </Button>
          </div>
        </Panel>
      </div>

    </div>
  );
}

export default ControlPage;
