// frontend/src/components/ui/ConfirmDialog.tsx
interface ConfirmDialogProps {
  open: boolean;
  title: string;
  message: string;
  confirmText?: string;
  cancelText?: string;
  danger?: boolean;
  onConfirm: () => void;
  onCancel: () => void;
}

export function ConfirmDialog({
  open,
  title,
  message,
  confirmText = '确认',
  cancelText = '取消',
  danger = false,
  onConfirm,
  onCancel,
}: ConfirmDialogProps) {
  if (!open) return null;

  return (
    <div className="aw-modal-backdrop z-[80]">
      <div className="aw-modal-panel max-w-md">
        <div className="border-b border-[var(--border-default)] px-5 py-4">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h3 className="text-base font-semibold text-white">{title}</h3>
              <p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">{message}</p>
            </div>
            <button onClick={onCancel} className="aw-modal-close" title="关闭">×</button>
          </div>
        </div>
        <div className="flex justify-end gap-2 px-5 py-4">
          <button onClick={onCancel} className="aw-confirm-cancel">
            {cancelText}
          </button>
          <button onClick={onConfirm} className={danger ? 'aw-confirm-danger' : 'aw-confirm-primary'}>
            {confirmText}
          </button>
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/ui/ConfirmDialog.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    open: boolean;
    title: string;
    message: string;
    confirmText?: string;
    cancelText?: string;
    danger?: boolean;
  }>(),
  { confirmText: "确认", cancelText: "取消" },
);
defineEmits<{ confirm: []; cancel: [] }>();
</script>
<template>
  <div v-if="open" class="aw-modal-backdrop z-[80]">
    <div class="aw-modal-panel max-w-md">
      <div class="border-b border-[var(--border-default)] px-5 py-4">
        <h3 class="text-base font-semibold">{{ title }}</h3>
        <p class="mt-2 text-sm text-[var(--text-secondary)]">{{ message }}</p>
      </div>
      <div class="flex justify-end gap-2 px-5 py-4">
        <button class="aw-confirm-cancel" @click="$emit('cancel')">
          {{ cancelText }}</button
        ><button
          :class="danger ? 'aw-confirm-danger' : 'aw-confirm-primary'"
          @click="$emit('confirm')"
        >
          {{ confirmText }}
        </button>
      </div>
    </div>
  </div>
</template>
