// frontend/src/components/ui/Modal.tsx
import React, { useState, useEffect, useCallback, useRef } from 'react';

interface ModalProps {
  open: boolean;
  onClose: () => void;
  title: string;
  width?: number;
  footer?: React.ReactNode;
  children: React.ReactNode;
  closable?: boolean;
  className?: string;
}

export function Modal({ open, onClose, title, width = 520, footer, children, closable = true, className = '' }: ModalProps) {
  const [visible, setVisible] = useState(false);
  const [exiting, setExiting] = useState(false);
  const panelRef = useRef<HTMLDivElement>(null);
  const prevFocusRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape' && closable) onClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, closable, onClose]);

  useEffect(() => {
    if (open) {
      prevFocusRef.current = document.activeElement as HTMLElement;
      setVisible(true);
      setExiting(false);
      document.body.style.overflow = 'hidden';
    } else if (visible) {
      setExiting(true);
      const timer = setTimeout(() => { setVisible(false); setExiting(false); document.body.style.overflow = ''; prevFocusRef.current?.focus(); }, 200);
      return () => clearTimeout(timer);
    }
    return () => { document.body.style.overflow = ''; };
  }, [open]);

  const handleBackdrop = useCallback(() => { if (closable) onClose(); }, [closable, onClose]);

  if (!visible) return null;

  return (
    <div className="fixed inset-0 z-[var(--z-modal)] flex items-center justify-center p-4" onClick={handleBackdrop} role="dialog" aria-modal="true" aria-label={title}>
      <div className={`absolute inset-0 bg-[var(--bg-overlay)] ${exiting ? 'animate-modal-overlay-out' : 'animate-modal-overlay-in'}`} />
      <div ref={panelRef} className={`relative bg-[rgba(15,27,44,0.96)] backdrop-blur-xl rounded-[var(--radius-xl)] shadow-[var(--shadow-xl)] border border-[var(--border-default)] w-full mx-auto focus-ring ${exiting ? 'animate-modal-content-out' : 'animate-modal-content-in'} ${className}`} style={{ maxWidth: width }} onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between px-6 py-4 border-b border-[var(--border-light)]">
          <h3 className="text-lg font-semibold text-[var(--text-primary)]">{title}</h3>
          {closable && (
            <button onClick={onClose} className="text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors focus-ring cursor-pointer" aria-label="Close">
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M12 4L4 12M4 4l8 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg>
            </button>
          )}
        </div>
        <div className="px-6 py-4">{children}</div>
        {footer && <div className="flex items-center justify-end gap-2 px-6 py-4 border-t border-[var(--border-light)]">{footer}</div>}
      </div>
    </div>
  );
}

// frontend/src/components/ui/Modal.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, watch } from "vue";
const p = withDefaults(
  defineProps<{
    open: boolean;
    title: string;
    width?: number;
    size?: "sm" | "md" | "lg" | "xl";
    closable?: boolean;
  }>(),
  { size: "md", closable: true },
);
const emit = defineEmits<{ close: [] }>();
const maxWidth = computed(
  () => p.width || { sm: 420, md: 520, lg: 760, xl: 1120 }[p.size],
);
const key = (e: KeyboardEvent) => {
  if (e.key === "Escape" && p.closable) emit("close");
};
watch(
  () => p.open,
  (v) => {
    document.body.style.overflow = v ? "hidden" : "";
    v
      ? document.addEventListener("keydown", key)
      : document.removeEventListener("keydown", key);
  },
  { immediate: true },
);
onBeforeUnmount(() => {
  document.body.style.overflow = "";
  document.removeEventListener("keydown", key);
});
</script>
<template>
  <Teleport to="body"
    ><div
      v-if="open"
      class="fixed inset-0 z-[var(--z-modal)] flex items-center justify-center p-4"
      role="dialog"
      aria-modal="true"
      @click.self="closable && $emit('close')"
    >
      <div class="absolute inset-0 bg-[var(--bg-overlay)]" />
      <div
        class="relative w-full rounded-[var(--radius-xl)] border border-[var(--border-default)] bg-[var(--bg-elevated)] shadow-[var(--shadow-xl)]"
        :style="{ maxWidth: `${maxWidth}px` }"
        @click.stop
      >
        <header
          class="flex items-center justify-between border-b border-[var(--border-light)] px-6 py-4"
        >
          <h3 class="text-lg font-semibold">{{ title }}</h3>
          <button v-if="closable" @click="$emit('close')">×</button>
        </header>
        <div class="px-6 py-4"><slot /></div>
        <footer
          v-if="$slots.footer"
          class="flex justify-end gap-2 border-t border-[var(--border-light)] px-6 py-4"
        >
          <slot name="footer" />
        </footer>
      </div></div
  ></Teleport>
</template>
