// frontend/src/components/ui/StatusBadge.vue
<script setup lang="ts">
import { computed } from "vue";
type S = "running" | "stopped" | "error" | "pending" | "online" | "offline";
const p = withDefaults(
  defineProps<{
    status: S;
    label?: string;
    pulse?: boolean;
    size?: "sm" | "md";
  }>(),
  { size: "md" },
);
const color: Record<S, string> = {
  running: "bg-[var(--color-success)]",
  online: "bg-[var(--color-success)]",
  stopped: "bg-[var(--text-disabled)]",
  offline: "bg-[var(--text-disabled)]",
  error: "bg-[var(--color-error)]",
  pending: "bg-[var(--color-warning)]",
};
const pulsing = computed(
  () => p.pulse ?? ["running", "online"].includes(p.status),
);
</script>
<template>
  <span class="inline-flex items-center gap-1.5"
    ><span
      class="inline-block rounded-full"
      :class="[
        color[status],
        size === 'sm' ? 'h-1.5 w-1.5' : 'h-2 w-2',
        pulsing && 'animate-status-pulse',
      ]"
    /><span v-if="label" class="text-sm text-[var(--text-secondary)]">{{
      label
    }}</span></span
  >
</template>

// frontend/src/components/ui/StatusBadge.tsx
type StatusType = 'running' | 'stopped' | 'error' | 'pending' | 'online' | 'offline';

interface StatusBadgeProps {
  status: StatusType;
  label?: string;
  pulse?: boolean;
  size?: 'sm' | 'md';
  className?: string;
}

const statusStyles: Record<StatusType, { dot: string; glow?: string }> = {
  running: { dot: 'bg-[var(--color-success)]', glow: '0 0 8px rgba(82,196,26,0.6)' },
  stopped: { dot: 'bg-[var(--text-disabled)]' },
  error: { dot: 'bg-[var(--color-error)]', glow: '0 0 8px rgba(255,77,79,0.5)' },
  pending: { dot: 'bg-[var(--color-warning)]', glow: '0 0 8px rgba(250,173,20,0.5)' },
  online: { dot: 'bg-[var(--color-success)]', glow: '0 0 8px rgba(82,196,26,0.6)' },
  offline: { dot: 'bg-[var(--text-disabled)]' },
};

const dotSizes = { sm: 'w-1.5 h-1.5', md: 'w-2 h-2' };

export function StatusBadge({ status, label, pulse, size = 'md', className = '' }: StatusBadgeProps) {
  const style = statusStyles[status];
  const shouldPulse = pulse ?? (status === 'running' || status === 'online');
  return (
    <span className={`inline-flex items-center gap-1.5 ${className}`}>
      <span className={`inline-block rounded-full ${style.dot} ${dotSizes[size]} ${shouldPulse ? 'animate-status-pulse' : ''}`} style={style.glow ? { boxShadow: style.glow } : undefined} />
      {label && <span className="text-sm text-[var(--text-secondary)]">{label}</span>}
    </span>
  );
}
