// frontend/src/components/ui/Toast.tsx
import { AlertTriangle, Check, Info } from 'lucide-react';

interface ToastProps {
  message: string;
  type?: 'success' | 'error' | 'info';
}

export function Toast({ message, type = 'info' }: ToastProps) {
  if (!message) return null;

  const tone = type === 'success' ? 'aw-toast-success' : type === 'error' ? 'aw-toast-error' : 'aw-toast-info';
  const label = type === 'success' ? '成功' : type === 'error' ? '失败' : '提示';
  const Icon = type === 'success' ? Check : type === 'error' ? AlertTriangle : Info;

  return (
    <div className="pointer-events-none fixed bottom-[13vh] left-1/2 z-[70] w-full max-w-xl -translate-x-1/2 px-4">
      <div className={`aw-toast ${tone}`} role={type === 'error' ? 'alert' : 'status'} aria-live={type === 'error' ? 'assertive' : 'polite'}>
        <span className="aw-toast-icon"><Icon size={19} strokeWidth={2.3} /></span>
        <span className="min-w-0">
          <span className="aw-toast-label">{label}</span>
          <span className="aw-toast-message">{message}</span>
        </span>
      </div>
    </div>
  );
}

// frontend/src/components/ui/Toast.vue
<script setup lang="ts">
import { AlertTriangle, Check, Info } from "lucide-vue-next";
import { computed } from "vue";
const p = withDefaults(
  defineProps<{ message: string; type?: "success" | "error" | "info" }>(),
  { type: "info" },
);
const icon = computed(() =>
  p.type === "success" ? Check : p.type === "error" ? AlertTriangle : Info,
);
</script>
<template>
  <div
    v-if="message"
    class="pointer-events-none fixed bottom-[13vh] left-1/2 z-[70] w-full max-w-xl -translate-x-1/2 px-4"
  >
    <div
      class="aw-toast"
      :class="`aw-toast-${type}`"
      :role="type === 'error' ? 'alert' : 'status'"
    >
      <span class="aw-toast-icon"><component :is="icon" :size="19" /></span
      ><span
        ><span class="aw-toast-label">{{
          type === "success" ? "成功" : type === "error" ? "失败" : "提示"
        }}</span
        ><span class="aw-toast-message">{{ message }}</span></span
      >
    </div>
  </div>
</template>
